# Generated by Django 6.0 on 2026-02-02 06:35

import cloudinary.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="About the Academy", max_length=200),
                ),
                ("history_text", django_ckeditor_5.fields.CKEditor5Field()),
                (
                    "history_image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="history image",
                    ),
                ),
                ("mission", django_ckeditor_5.fields.CKEditor5Field()),
                ("vision", django_ckeditor_5.fields.CKEditor5Field()),
                ("aims_and_objectives", django_ckeditor_5.fields.CKEditor5Field()),
            ],
            options={
                "verbose_name_plural": "About Page Content",
            },
        ),
        migrations.CreateModel(
            name="EmailUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Internal name for admins",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "message",
                    models.TextField(
                        help_text="Email body (supports {{username}} placeholder)"
                    ),
                ),
                (
                    "sendgrid_template_id",
                    models.CharField(
                        blank=True,
                        help_text="SendGrid dynamic template ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only one template can be active at a time",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("exco", "Executive Member"),
                            ("trustee", "Board of Trustees"),
                            ("committee_director", "Committee Director"),
                        ],
                        db_index=True,
                        help_text="Role type - standardized values only",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "permissions_level",
                    models.IntegerField(
                        default=1, help_text="Higher number = more authority (1-10)"
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "ordering": ["-permissions_level"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "profile_picture",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                (
                    "membership_tier",
                    models.CharField(
                        choices=[
                            ("student", "Student Member"),
                            ("associate", "Associate Member"),
                            ("full", "Full Member"),
                            ("fellow", "Fellow"),
                        ],
                        db_index=True,
                        default="student",
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Nigerian phone number",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in format: '+2348012345678' or '08012345678'",
                                regex="^\\+?234?\\d{10}$",
                            )
                        ],
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Admin-verified member status",
                    ),
                ),
                (
                    "date_verified",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True, related_name="users", to="accounts.role"
                    ),
                ),
            ],
            options={
                "verbose_name": "NAA Member",
                "verbose_name_plural": "NAA Members",
                "db_table": "accounts_user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Committee name (e.g., SCOPHA, Education Committee)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of committee purpose"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "director",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="directed_committees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="committees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Committee",
                "verbose_name_plural": "Committees",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Executive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="e.g., National President, Vice President",
                        max_length=100,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Short bio displayed on homepage"
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Display order (1 for President, 2 for VP, etc.)",
                    ),
                ),
                ("term_start_date", models.DateField()),
                ("term_end_date", models.DateField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Active executives shown on homepage"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executive_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Executive Officer",
                "verbose_name_plural": "Executive Officers",
                "ordering": ["rank"],
            },
        ),
        migrations.CreateModel(
            name="StudentAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Short preview shown in listings"
                    ),
                ),
                ("content", django_ckeditor_5.fields.CKEditor5Field()),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Uncheck to hide this announcement",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Featured announcements appear first"
                    ),
                ),
                ("date_posted", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_university",
                    models.CharField(
                        choices=[
                            ("All", "All Universities"),
                            ("UNIMED", "University of Medical Sciences, Ondo"),
                            (
                                "FUHSI",
                                "Federal University of Health Sciences, Ila-Orangun",
                            ),
                            ("FUHSA", "Federal University of Health Sciences, Azare"),
                            ("FUDMA", "Federal University Dutsin-Ma, Katsina"),
                        ],
                        db_index=True,
                        default="All",
                        help_text="Target specific university or all",
                        max_length=20,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who created this announcement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Announcement",
                "verbose_name_plural": "Student Announcements",
                "ordering": ["-date_posted"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "university",
                    models.CharField(
                        choices=[
                            ("UNIMED", "University of Medical Sciences, Ondo (UNIMED)"),
                            (
                                "FUHSI",
                                "Federal University of Health Sciences, Ila-Orangun (FUHSI)",
                            ),
                            (
                                "FUHSA",
                                "Federal University of Health Sciences, Azare (FUHSA)",
                            ),
                            ("FUDMA", "Federal University Dutsin-Ma, Katsina (FUDMA)"),
                        ],
                        db_index=True,
                        help_text="Select your university",
                        max_length=100,
                    ),
                ),
                (
                    "matric_number",
                    models.CharField(
                        help_text="University matriculation number",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (100, "100 Level"),
                            (200, "200 Level"),
                            (300, "300 Level"),
                            (400, "400 Level"),
                            (500, "500 Level"),
                        ],
                        help_text="Current academic level",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Profile",
                "verbose_name_plural": "Student Profiles",
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Short preview shown in listings"
                    ),
                ),
                ("content", django_ckeditor_5.fields.CKEditor5Field()),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Uncheck to hide this announcement",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Featured announcements appear first"
                    ),
                ),
                ("date_posted", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who created this announcement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "National Announcement",
                "verbose_name_plural": "National Announcements",
                "ordering": ["-featured", "-date_posted"],
                "indexes": [
                    models.Index(
                        fields=["-date_posted", "is_published"],
                        name="accounts_an_date_po_0a4148_idx",
                    ),
                    models.Index(
                        fields=["featured", "-date_posted"],
                        name="accounts_an_feature_743e66_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("content", django_ckeditor_5.fields.CKEditor5Field()),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft/Pending Review"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "is_public", "-created_at"],
                        name="accounts_ar_status_24b16a_idx",
                    ),
                    models.Index(fields=["slug"], name="accounts_ar_slug_2ac734_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommitteeAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Short preview shown in listings"
                    ),
                ),
                ("content", django_ckeditor_5.fields.CKEditor5Field()),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Uncheck to hide this announcement",
                    ),
                ),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Featured announcements appear first"
                    ),
                ),
                ("date_posted", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who created this announcement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        help_text="Which committee this announcement is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="accounts.committee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Committee Announcement",
                "verbose_name_plural": "Committee Announcements",
                "ordering": ["-date_posted"],
                "indexes": [
                    models.Index(
                        fields=["committee", "-date_posted"],
                        name="accounts_co_committ_9e1f5e_idx",
                    ),
                    models.Index(
                        fields=["is_published", "-date_posted"],
                        name="accounts_co_is_publ_7a127c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommitteeReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="committee_reports/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="accounts.committee",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Committee Report",
                "verbose_name_plural": "Committee Reports",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["committee", "-uploaded_at"],
                        name="accounts_co_committ_ad5293_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CPDRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_name",
                    models.CharField(
                        help_text="e.g., NAA Annual Conference 2026", max_length=255
                    ),
                ),
                ("date_completed", models.DateField(db_index=True)),
                ("points", models.PositiveIntegerField(default=5)),
                (
                    "certificate",
                    models.FileField(
                        blank=True,
                        help_text="Upload PDF proof of participation",
                        null=True,
                        upload_to="cpd_certificates/",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Admin verification status",
                    ),
                ),
                ("date_recorded", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cpd_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CPD Record",
                "verbose_name_plural": "CPD Records",
                "ordering": ["-date_completed"],
                "indexes": [
                    models.Index(
                        fields=["user", "-date_completed"],
                        name="accounts_cp_user_id_5c6c01_idx",
                    ),
                    models.Index(
                        fields=["is_verified"], name="accounts_cp_is_veri_d02262_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", django_ckeditor_5.fields.CKEditor5Field()),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="accounts_no_user_id_b29cd4_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("guideline", "Clinical Guideline"),
                            ("academic", "Study Material"),
                            ("research", "Research Paper"),
                            ("governance", "Academy Document"),
                            ("legal", "Legal/Ethics"),
                            ("general", "General Information"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="resources/")),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("public", "General/Public"),
                            ("student", "Student Only"),
                            ("associate", "Associate & Above"),
                            ("full", "Full Members & Above"),
                            ("fellow", "Fellows Only"),
                        ],
                        db_index=True,
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "is_verified_only",
                    models.BooleanField(
                        default=True, help_text="Only verified members can download"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource",
                "verbose_name_plural": "Resources",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "access_level"],
                        name="accounts_re_categor_cce638_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["membership_tier", "is_verified"],
                name="accounts_us_members_e23129_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="accounts_us_email_74c8d6_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["-date_joined"], name="accounts_us_date_jo_bab293_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentannouncement",
            index=models.Index(
                fields=["target_university", "-date_posted"],
                name="accounts_st_target__d80c59_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentannouncement",
            index=models.Index(
                fields=["is_published", "-date_posted"],
                name="accounts_st_is_publ_f93aba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentprofile",
            index=models.Index(
                fields=["university"], name="accounts_st_univers_31af11_idx"
            ),
        ),
    ]
