# Generated by Django 6.0 on 2026-02-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="expected_graduation_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The year the student is expected to graduate (e.g., 2027)",
                null=True,
            ),
        ),
    ]
