# Generated by Django 6.0 on 2026-01-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="About the Academy", max_length=200),
                ),
                ("history_text", models.TextField(help_text="The history of NAA")),
                (
                    "history_image",
                    models.ImageField(blank=True, null=True, upload_to="about/"),
                ),
                ("mission", models.TextField()),
                ("vision", models.TextField()),
                (
                    "aims_and_objectives",
                    models.TextField(help_text="Separate objectives with a new line"),
                ),
            ],
            options={
                "verbose_name_plural": "About Page Content",
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("student", "Student Resource"),
                            ("clinical", "Clinical Guidelines"),
                            ("research", "Research Papers"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="resources/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_members_only", models.BooleanField(default=True)),
            ],
        ),
    ]
