# Generated by Django 6.0 on 2026-01-04 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_aboutpage_resource"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="is_members_only",
        ),
        migrations.AddField(
            model_name="resource",
            name="is_public",
            field=models.BooleanField(default=False, help_text="Can anyone see this?"),
        ),
        migrations.AddField(
            model_name="resource",
            name="is_verified_only",
            field=models.BooleanField(
                default=True, help_text="Only verified members can download"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="category",
            field=models.CharField(
                choices=[
                    ("student", "Student Resource"),
                    ("clinical", "Clinical Guidelines"),
                    ("research", "Research Papers"),
                    ("admin", "Administrative Docs"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "university",
                    models.CharField(
                        choices=[
                            ("UNIMED", "University of Medical Sciences, Ondo (UNIMED)"),
                            (
                                "FUHSI",
                                "Federal University of Health Sciences, Ila-Orangun (FUHSI)",
                            ),
                            (
                                "FUHSA",
                                "Federal University of Health Sciences, Azare (FUHSA)",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                ("matric_number", models.CharField(max_length=20, unique=True)),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (100, "100L"),
                            (200, "200L"),
                            (300, "300L"),
                            (400, "400L"),
                            (500, "500L"),
                        ]
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
