# Generated by Django 6.0 on 2026-02-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_studentprofile_expected_graduation_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="expected_graduation_year",
        ),
    ]
