# Generated by Django 6.0 on 2026-01-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_remove_resource_is_members_only_resource_is_public_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                (
                    "target_university",
                    models.CharField(
                        choices=[
                            ("All", "All Universities"),
                            ("UNIMED", "UNIMED"),
                            ("FUHSI", "FUHSI"),
                            ("FUHSA", "FUHSA"),
                        ],
                        default="All",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
