# Generated by Django 6.0 on 2026-01-04 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentannouncement_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPDRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('date_completed', models.DateField()),
                ('certificate', models.FileField(blank=True, null=True, upload_to='cpd_certs/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpd_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
