# Generated by Django 6.0 on 2026-01-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_resource_options_remove_resource_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='university',
            field=models.CharField(choices=[('UNIMED', 'University of Medical Sciences, Ondo (UNIMED)'), ('FUHSI', 'Federal University of Health Sciences, Ila-Orangun (FUHSI)'), ('FUHSA', 'Federal University of Health Sciences, Azare (FUHSA)'), ('futminna', 'Federal University of Technology, Minna')], max_length=100),
        ),
    ]
