# Generated by Django 6.0 on 2026-01-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_studentprofile_university"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="university",
            field=models.CharField(
                choices=[
                    ("UNIMED", "University of Medical Sciences, Ondo (UNIMED)"),
                    (
                        "FUHSI",
                        "Federal University of Health Sciences, Ila-Orangun (FUHSI)",
                    ),
                    ("FUHSA", "Federal University of Health Sciences, Azare (FUHSA)"),
                    ("FUDMA", "Federal University Dutsin-Ma, Katsina (FUDMA)"),
                ],
                max_length=100,
            ),
        ),
    ]
