# Generated by Django 6.0 on 2026-01-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_studentprofile_university"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Internal name for admins", max_length=200
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "message",
                    models.TextField(help_text="Email body (plain text for now)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
