# Generated by Django 6.0 on 2026-01-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_remove_user_sendgrid_template_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_verified",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
