# Generated by Django 6.0 on 2026-01-24 15:06

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_announcement_author_announcement_featured_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
