# Generated by Django 6.0 on 2026-01-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_executive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leader',
        ),
        migrations.AddField(
            model_name='executive',
            name='bio',
            field=models.TextField(blank=True, help_text='A short introductory text about the officer (shows on Home Page).', null=True),
        ),
    ]
