# Generated by Django 6.0 on 2026-01-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_delete_leader_executive_bio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ["-permissions_level"]},
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("exco", "Executive Committee Member"),
                    ("trustee", "Board of Trustees Member"),
                    ("committee_director", "Committee Director"),
                ],
                help_text="Role type - cannot be changed after creation",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="permissions_level",
            field=models.IntegerField(
                default=1, help_text="Higher number = more authority"
            ),
        ),
    ]
