# Generated by Django 6.0 on 2026-01-31 18:29

import accounts.validators
import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0028_merge_20260131_1917"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={
                "ordering": ["-featured", "-date_posted"],
                "verbose_name": "National Announcement",
                "verbose_name_plural": "National Announcements",
            },
        ),
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="committeereport",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Committee Report",
                "verbose_name_plural": "Committee Reports",
            },
        ),
        migrations.AlterModelOptions(
            name="cpdrecord",
            options={
                "ordering": ["-date_completed"],
                "verbose_name": "CPD Record",
                "verbose_name_plural": "CPD Records",
            },
        ),
        migrations.AlterModelOptions(
            name="studentprofile",
            options={
                "verbose_name": "Student Profile",
                "verbose_name_plural": "Student Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "NAA Member",
                "verbose_name_plural": "NAA Members",
            },
        ),
        migrations.RemoveIndex(
            model_name="committeeannouncement",
            name="commann_comm_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="cpdrecord",
            name="cpd_user_date_idx",
        ),
        migrations.RenameIndex(
            model_name="announcement",
            new_name="accounts_an_date_po_0a4148_idx",
            old_name="announcement_date_pub_idx",
        ),
        migrations.RenameIndex(
            model_name="announcement",
            new_name="accounts_an_feature_743e66_idx",
            old_name="announcement_featured_idx",
        ),
        migrations.RenameIndex(
            model_name="article",
            new_name="accounts_ar_status_24b16a_idx",
            old_name="article_status_idx",
        ),
        migrations.RenameIndex(
            model_name="committeereport",
            new_name="accounts_co_committ_ad5293_idx",
            old_name="report_comm_date_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="accounts_no_user_id_b29cd4_idx",
            old_name="notif_user_read_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="accounts_us_members_e23129_idx",
            old_name="user_tier_verified_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="accounts_us_email_74c8d6_idx",
            old_name="user_email_idx",
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="history_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    accounts.validators.validate_image_file,
                    accounts.validators.validate_file_name,
                ],
                verbose_name="history image",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    accounts.validators.validate_image_file,
                    accounts.validators.validate_file_name,
                ],
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    accounts.validators.validate_image_file,
                    accounts.validators.validate_file_name,
                ],
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="committeereport",
            name="file",
            field=models.FileField(
                upload_to="committee_reports/",
                validators=[
                    accounts.validators.validate_pdf_file,
                    accounts.validators.validate_file_name,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="cpdrecord",
            name="certificate",
            field=models.FileField(
                blank=True,
                help_text="Upload PDF or Image proof of participation",
                null=True,
                upload_to="cpd_certificates/",
                validators=[
                    accounts.validators.validate_pdf_file,
                    accounts.validators.validate_file_name,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="emailupdate",
            name="title",
            field=models.CharField(
                help_text="Internal name for admins", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="file",
            field=models.FileField(
                upload_to="resources/",
                validators=[
                    accounts.validators.validate_pdf_file,
                    accounts.validators.validate_file_name,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("exco", "Executive Committee Member"),
                    ("trustee", "Board of Trustees Member"),
                    ("committee_director", "Committee Director"),
                ],
                help_text="Role type - cannot be changed after creation",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="matric_number",
            field=models.CharField(
                help_text="Your university matriculation number",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="university",
            field=models.CharField(
                choices=[
                    ("UNIMED", "University of Medical Sciences, Ondo (UNIMED)"),
                    (
                        "FUHSI",
                        "Federal University of Health Sciences, Ila-Orangun (FUHSI)",
                    ),
                    ("FUHSA", "Federal University of Health Sciences, Azare (FUHSA)"),
                    ("FUDMA", "Federal University Dutsin-Ma, Katsina (FUDMA)"),
                ],
                help_text="Select your university",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Nigerian phone number",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in format: '+2348012345678' or '08012345678'",
                        regex="^\\+?234?\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    accounts.validators.validate_image_file,
                    accounts.validators.validate_file_name,
                ],
                verbose_name="image",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["slug"], name="accounts_ar_slug_2ac734_idx"),
        ),
        migrations.AddIndex(
            model_name="cpdrecord",
            index=models.Index(
                fields=["user", "-date_completed"], name="cpd_user_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cpdrecord",
            index=models.Index(
                fields=["is_verified"], name="accounts_cp_is_veri_d02262_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["-date_joined"], name="accounts_us_date_jo_bab293_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="accounts_user",
        ),
    ]
