# Generated by Django 6.0 on 2026-01-31 20:13

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_committeeannouncement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='committee',
            options={'ordering': ['name'], 'verbose_name': 'Committee', 'verbose_name_plural': 'Committees'},
        ),
        migrations.AlterModelOptions(
            name='emailupdate',
            options={'verbose_name': 'Email Template', 'verbose_name_plural': 'Email Templates'},
        ),
        migrations.AlterModelOptions(
            name='executive',
            options={'ordering': ['rank'], 'verbose_name': 'Executive Officer', 'verbose_name_plural': 'Executive Officers'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-permissions_level'], 'verbose_name': 'User Role', 'verbose_name_plural': 'User Roles'},
        ),
        migrations.RenameIndex(
            model_name='cpdrecord',
            new_name='accounts_cp_user_id_5c6c01_idx',
            old_name='cpd_user_date_idx',
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='committee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='committee',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of committee purpose'),
        ),
        migrations.AddField(
            model_name='committee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='executive',
            name='term_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='history_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='history image'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide this announcement'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='summary',
            field=models.TextField(blank=True, help_text='Short preview shown in listings'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft/Pending Review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='committee',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_committees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='committee',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='committees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(db_index=True, help_text='Committee name (e.g., SCOPHA, Education Committee)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='committeeannouncement',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='committeeannouncement',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide this announcement'),
        ),
        migrations.AlterField(
            model_name='committeeannouncement',
            name='summary',
            field=models.TextField(blank=True, help_text='Short preview shown in listings'),
        ),
        migrations.AlterField(
            model_name='committeereport',
            name='file',
            field=models.FileField(upload_to='committee_reports/'),
        ),
        migrations.AlterField(
            model_name='committeereport',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cpdrecord',
            name='certificate',
            field=models.FileField(blank=True, help_text='Upload PDF proof of participation', null=True, upload_to='cpd_certificates/'),
        ),
        migrations.AlterField(
            model_name='cpdrecord',
            name='date_completed',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cpdrecord',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Admin verification status'),
        ),
        migrations.AlterField(
            model_name='emailupdate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one template can be active at a time'),
        ),
        migrations.AlterField(
            model_name='emailupdate',
            name='message',
            field=models.TextField(help_text='Email body (supports {{username}} placeholder)'),
        ),
        migrations.AlterField(
            model_name='emailupdate',
            name='sendgrid_template_id',
            field=models.CharField(blank=True, help_text='SendGrid dynamic template ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emailupdate',
            name='title',
            field=models.CharField(help_text='Internal name for admins', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='executive',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Short bio displayed on homepage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='executive',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active executives shown on homepage'),
        ),
        migrations.AlterField(
            model_name='executive',
            name='position',
            field=models.CharField(help_text='e.g., National President, Vice President', max_length=100),
        ),
        migrations.AlterField(
            model_name='executive',
            name='rank',
            field=models.PositiveIntegerField(default=1, help_text='Display order (1 for President, 2 for VP, etc.)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='access_level',
            field=models.CharField(choices=[('public', 'General/Public'), ('student', 'Student Only'), ('associate', 'Associate & Above'), ('full', 'Full Members & Above'), ('fellow', 'Fellows Only')], db_index=True, default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('guideline', 'Clinical Guideline'), ('academic', 'Study Material'), ('research', 'Research Paper'), ('governance', 'Academy Document'), ('legal', 'Legal/Ethics'), ('general', 'General Information')], db_index=True, default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='is_verified_only',
            field=models.BooleanField(default=True, help_text='Only verified members can download'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('exco', 'Executive Committee Member'), ('trustee', 'Board of Trustees Member'), ('committee_director', 'Committee Director')], db_index=True, help_text='Role type - standardized values only', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions_level',
            field=models.IntegerField(default=1, help_text='Higher number = more authority (1-10)'),
        ),
        migrations.AlterField(
            model_name='studentannouncement',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='studentannouncement',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide this announcement'),
        ),
        migrations.AlterField(
            model_name='studentannouncement',
            name='summary',
            field=models.TextField(blank=True, help_text='Short preview shown in listings'),
        ),
        migrations.AlterField(
            model_name='studentannouncement',
            name='target_university',
            field=models.CharField(choices=[('All', 'All Universities'), ('UNIMED', 'University of Medical Sciences, Ondo'), ('FUHSI', 'Federal University of Health Sciences, Ila-Orangun'), ('FUHSA', 'Federal University of Health Sciences, Azare'), ('FUDMA', 'Federal University Dutsin-Ma, Katsina')], db_index=True, default='All', help_text='Target specific university or all', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.IntegerField(choices=[(100, '100 Level'), (200, '200 Level'), (300, '300 Level'), (400, '400 Level'), (500, '500 Level')], help_text='Current academic level'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='matric_number',
            field=models.CharField(help_text='University matriculation number', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='university',
            field=models.CharField(choices=[('UNIMED', 'University of Medical Sciences, Ondo (UNIMED)'), ('FUHSI', 'Federal University of Health Sciences, Ila-Orangun (FUHSI)'), ('FUHSA', 'Federal University of Health Sciences, Azare (FUHSA)'), ('FUDMA', 'Federal University Dutsin-Ma, Katsina (FUDMA)')], db_index=True, help_text='Select your university', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Admin-verified member status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_tier',
            field=models.CharField(choices=[('student', 'Student Member'), ('associate', 'Associate Member'), ('full', 'Full Member'), ('fellow', 'Fellow')], db_index=True, default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddIndex(
            model_name='committeeannouncement',
            index=models.Index(fields=['is_published', '-date_posted'], name='accounts_co_is_publ_7a127c_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['category', 'access_level'], name='accounts_re_categor_cce638_idx'),
        ),
        migrations.AddIndex(
            model_name='studentannouncement',
            index=models.Index(fields=['is_published', '-date_posted'], name='accounts_st_is_publ_f93aba_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['university'], name='accounts_st_univers_31af11_idx'),
        ),
    ]
